# Generated by Django 3.2.2 on 2021-05-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0017_movieupdateinformation_user'),
        ('user', '0001_initial'),
    ]

    operations = [
    ]
