# Generated by Django 3.2.2 on 2021-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0018_auto_20210518_2335'),
        ('user', '0003_user_can_edit_all_channel'),
    ]

    operations = [
    ]
