# Generated by Django 3.2.2 on 2021-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210519_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_applied',
            field=models.BooleanField(default=False, verbose_name='作者情報申請済み'),
        ),
    ]
