# Generated by Django 3.0.2 on 2020-05-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='アーティスト名')),
                ('name_kana', models.CharField(blank=True, max_length=200, null=True, verbose_name='アーティスト名カナ')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songdata.Artist', verbose_name='担当声優')),
                ('parent', models.ManyToManyField(blank=True, related_name='_artist_parent_+', to='songdata.Artist', verbose_name='所属グループ等')),
                ('related', models.ManyToManyField(blank=True, related_name='_artist_related_+', to='songdata.Artist', verbose_name='関連アーティスト')),
            ],
            options={
                'ordering': ('name_kana', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='曲名')),
                ('name_kana', models.CharField(blank=True, max_length=200, null=True, verbose_name='曲名カナ')),
                ('tieup', models.CharField(blank=True, max_length=400, null=True, verbose_name='タイアップ等')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='説明')),
                ('artist', models.ManyToManyField(blank=True, to='songdata.Artist', verbose_name='アーティスト')),
                ('parent', models.ManyToManyField(blank=True, related_name='_song_parent_+', to='songdata.Song', verbose_name='原作等')),
            ],
            options={
                'ordering': ('name_kana', 'name'),
            },
        ),
    ]
