# Generated by Django 3.0.2 on 2020-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='原作URL'),
        ),
    ]
