# Generated by Django 3.0.2 on 2020-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdata', '0002_song_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocalNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ボーカル名')),
                ('name_kana', models.CharField(blank=True, max_length=200, null=True, verbose_name='ボーカル名カナ')),
            ],
            options={
                'ordering': ('name_kana', 'name'),
            },
        ),
    ]
