# Generated by Django 3.2.2 on 2021-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdata', '0003_vocalnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='曲名')),
                ('song_name_kana', models.CharField(blank=True, max_length=200, null=True, verbose_name='曲名カナ')),
                ('artist_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='アーティスト名')),
                ('artist_name_kana', models.CharField(blank=True, max_length=400, null=True, verbose_name='アーティスト名カナ')),
                ('tag', models.CharField(blank=True, max_length=400, null=True, verbose_name='タグ')),
            ],
        ),
    ]
