# Generated by Django 3.2.2 on 2021-05-19 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songdata', '0005_auto_20210515_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='songnew',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
    ]
