# Generated by Django 3.2.2 on 2021-06-12 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdata', '0006_songnew_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songnew',
            name='artist_name_kana',
            field=models.TextField(blank=True, max_length=400, null=True, validators=[django.core.validators.RegexValidator(message='全角カタカナのみを入力してください', regex='^[ァ-ヶ\\s（）]+$')], verbose_name='アーティスト名カナ'),
        ),
        migrations.AlterField(
            model_name='songnew',
            name='song_name_kana',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='全角カタカナのみを入力してください', regex='^[ァ-ヶ]+$')], verbose_name='曲名カナ'),
        ),
        migrations.AlterField(
            model_name='vocalnew',
            name='name_kana',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='全角カタカナのみを入力してください', regex='^[ァ-ヶ]+$')], verbose_name='ボーカル名カナ'),
        ),
    ]
