# Generated by Django 4.0.3 on 2022-08-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdata', '0008_auto_20210613_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songnew',
            options={'ordering': ['song_name_kana', 'artist_name_kana']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='parent',
            field=models.ManyToManyField(blank=True, to='songdata.artist', verbose_name='所属グループ等'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='related',
            field=models.ManyToManyField(blank=True, to='songdata.artist', verbose_name='関連アーティスト'),
        ),
        migrations.AlterField(
            model_name='song',
            name='parent',
            field=models.ManyToManyField(blank=True, to='songdata.song', verbose_name='原作等'),
        ),
    ]
