# Generated by Django 3.0.2 on 2020-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0002_errorlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='station',
            name='lon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='経度'),
        ),
    ]
