# Generated by Django 3.0.2 on 2020-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0007_station_is_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stationservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stationservicehistory',
            name='category_history',
        ),
        migrations.AddField(
            model_name='belongscategory',
            name='object_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='名称カテゴリー'),
        ),
        migrations.DeleteModel(
            name='ObjectCategory',
        ),
    ]
