# Generated by Django 3.0.2 on 2020-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0008_auto_20200604_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='belongscategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FontAweSomeアイコン名称'),
        ),
        migrations.AlterField(
            model_name='lineservice',
            name='sort_by_company',
            field=models.IntegerField(default=999, verbose_name='事業者ごとの並び順'),
        ),
    ]
