# Generated by Django 3.2.2 on 2021-06-12 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdata', '0007_auto_20210612_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songnew',
            name='artist_name_kana',
            field=models.TextField(blank=True, max_length=400, null=True, validators=[django.core.validators.RegexValidator(message='全角カタカナのみを入力してください', regex='^[ァ-ヶ\\s（）ー]+$')], verbose_name='アーティスト名カナ'),
        ),
        migrations.AlterField(
            model_name='songnew',
            name='song_name_kana',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='全角カタカナのみを入力してください', regex='^[ァ-ヶー]+$')], verbose_name='曲名カナ'),
        ),
        migrations.AlterField(
            model_name='vocalnew',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='ボーカル名'),
        ),
        migrations.AlterField(
            model_name='vocalnew',
            name='name_kana',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='全角カタカナのみを入力してください', regex='^[ァ-ヶー]+$')], verbose_name='ボーカル名カナ'),
        ),
    ]
