# Generated by Django 3.0.7 on 2020-06-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0005_noticeinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='リンク名')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
            ],
        ),
        migrations.AlterModelOptions(
            name='movieupdateinformation',
            options={'ordering': ['-reg_date']},
        ),
        migrations.AlterModelOptions(
            name='noticeinformation',
            options={'ordering': ['-reg_date']},
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='メインチャンネル'),
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名前')),
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Creator', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='NiconicoAccount',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='niconicoアカウント名')),
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=True, verbose_name='メインアカウント')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Creator', verbose_name='作者')),
            ],
        ),
    ]
