# Generated by Django 3.2.2 on 2021-05-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0015_movieupdateinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieupdateinformation',
            name='user',
        ),
    ]
