# Generated by Django 3.2.2 on 2021-05-19 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviedatabase', '0020_updatehistory'),
    ]

    operations = [
    ]
