# Generated by Django 3.2.2 on 2021-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0023_accountandcreatorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecategory',
            name='object_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='歌唱オブジェクト名'),
        ),
    ]
