# Generated by Django 3.2.2 on 2021-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0028_movie_statistics_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
