# Generated by Django 3.0.2 on 2020-05-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stationdata', '0001_initial'),
        ('songdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='作者名')),
                ('name_kana', models.CharField(max_length=200, verbose_name='読み')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='動画タイトル')),
                ('main_id', models.CharField(max_length=200, unique=True, verbose_name='動画ID')),
                ('youtube_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='YouTube 動画ID')),
                ('niconico_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ニコニコ動画 動画ID')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='長さ')),
                ('n_view', models.IntegerField(blank=True, default=0, null=True, verbose_name='再生回数')),
                ('n_like', models.IntegerField(blank=True, default=0, null=True, verbose_name='高評価数')),
                ('n_dislike', models.IntegerField(blank=True, default=0, null=True, verbose_name='低評価数')),
                ('n_comment', models.IntegerField(blank=True, default=0, null=True, verbose_name='コメント数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('reg_date', models.DateTimeField(blank=True, null=True, verbose_name='データベース登録日時')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='データベース更新日時')),
                ('is_collab', models.CharField(choices=[('S', '単作'), ('C', '合作')], default='S', max_length=1, verbose_name='単作or合作')),
                ('explanation', models.TextField(blank=True, verbose_name='補足説明')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='動画カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名義')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_name', to='moviedatabase.Creator', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_by_movie', models.IntegerField()),
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='パート名')),
                ('start_time', models.DurationField(blank=True, default='00:00:00', null=True, verbose_name='開始時間')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='補足説明')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.MovieCategory', verbose_name='カテゴリー')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Movie', to_field='main_id', verbose_name='動画')),
                ('participant', models.ManyToManyField(blank=True, to='moviedatabase.Name', verbose_name='参加名義')),
                ('song', models.ManyToManyField(blank=True, to='songdata.Song', verbose_name='使用楽曲(パート)')),
            ],
        ),
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ボーカル名')),
                ('name_kana', models.CharField(blank=True, max_length=200, null=True, verbose_name='ボーカル名カナ')),
            ],
            options={
                'ordering': ('name_kana', 'name'),
            },
        ),
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='YouTubeチャンネル名')),
                ('channel_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Creator', verbose_name='作者')),
                ('main_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Name', verbose_name='チャンネル名義')),
            ],
        ),
        migrations.CreateModel(
            name='StationInMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_by_part', models.IntegerField()),
                ('sung_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='歌唱名')),
                ('back_rel', models.IntegerField(default=1, verbose_name='前駅との関係')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Part', verbose_name='動画パート')),
                ('station_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.StationService', verbose_name='駅')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='vocal',
            field=models.ManyToManyField(blank=True, to='moviedatabase.Vocal', verbose_name='使用ボーカル(パート)'),
        ),
        migrations.CreateModel(
            name='MovieUpdateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.CharField(choices=[('C', '新規登録'), ('U', '更新')], default='C', max_length=1, verbose_name='新規登録か更新か')),
                ('reg_date', models.DateTimeField(blank=True, verbose_name='登録・更新日時')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Movie', to_field='main_id', verbose_name='動画')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.YoutubeChannel', verbose_name='投稿チャンネル'),
        ),
        migrations.AddField(
            model_name='movie',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_movie_parent_+', to='moviedatabase.Movie', verbose_name='親作品'),
        ),
        migrations.AddField(
            model_name='movie',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_movie_related_+', to='moviedatabase.Movie', verbose_name='関連作品'),
        ),
        migrations.AddField(
            model_name='movie',
            name='song',
            field=models.ManyToManyField(blank=True, to='songdata.Song', verbose_name='使用楽曲(動画全体)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vocal',
            field=models.ManyToManyField(blank=True, to='moviedatabase.Vocal', verbose_name='使用ボーカル(動画全体)'),
        ),
        migrations.CreateModel(
            name='LineInMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.LineService', verbose_name='路線')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Part', verbose_name='動画パート')),
            ],
        ),
    ]
