# Generated by Django 3.0.7 on 2020-06-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0009_pagelink_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieupdateinformation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.Creator', verbose_name='作者'),
        ),
    ]
