# Generated by Django 3.2.2 on 2021-05-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0010_movieupdateinformation_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('is_collab', '-id')},
        ),
    ]
