# Generated by Django 3.2.2 on 2021-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdata', '0004_songnew'),
        ('moviedatabase', '0011_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='songnew',
            field=models.ManyToManyField(blank=True, to='songdata.SongNew', verbose_name='使用楽曲(楽曲全体)'),
        ),
        migrations.AddField(
            model_name='part',
            name='songnew',
            field=models.ManyToManyField(blank=True, to='songdata.SongNew', verbose_name='使用楽曲(パート)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='song',
            field=models.ManyToManyField(blank=True, to='songdata.Song', verbose_name='使用楽曲(動画全体)(旧)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='song',
            field=models.ManyToManyField(blank=True, to='songdata.Song', verbose_name='使用楽曲(パート)(旧)'),
        ),
    ]
