# Generated by Django 3.2.2 on 2021-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0012_auto_20210515_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
