# Generated by Django 3.2.2 on 2021-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0013_alter_part_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinmovie',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='補足説明'),
        ),
    ]
