# Generated by Django 3.2.2 on 2021-05-18 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviedatabase', '0014_stationinmovie_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieupdateinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='編集者'),
        ),
    ]
