# Generated by Django 3.2.2 on 2021-05-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0017_movieupdateinformation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['name_kana', 'name']},
        ),
        migrations.AlterModelOptions(
            name='youtubechannel',
            options={'ordering': ['creator', '-is_main']},
        ),
    ]
