# Generated by Django 3.2.2 on 2021-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0021_updatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatehistory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='種別'),
        ),
    ]
