# Generated by Django 3.2.2 on 2021-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0024_moviecategory_object_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='incomplete',
            field=models.BooleanField(default=False, verbose_name='情報が不完全'),
        ),
    ]
