# Generated by Django 3.2.2 on 2021-05-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0025_part_incomplete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ファイル名')),
                ('text', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
    ]
