# Generated by Django 3.2.2 on 2021-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0026_topimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountandcreatorapplication',
            name='dealing',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='動画の扱い'),
        ),
    ]
