# Generated by Django 3.2.2 on 2021-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0027_accountandcreatorapplication_dealing'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='statistics_update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='統計情報更新日時'),
        ),
    ]
