# Generated by Django 3.2.2 on 2021-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0029_youtubechannel_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published_at_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='投稿日時[日本時間]（日）'),
        ),
        migrations.AddField(
            model_name='movie',
            name='published_at_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='投稿日時[日本時間]（時）'),
        ),
        migrations.AddField(
            model_name='movie',
            name='published_at_minute',
            field=models.IntegerField(blank=True, null=True, verbose_name='投稿日時[日本時間]（分）'),
        ),
        migrations.AddField(
            model_name='movie',
            name='published_at_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='投稿日時[日本時間]（月）'),
        ),
        migrations.AddField(
            model_name='movie',
            name='published_at_second',
            field=models.IntegerField(blank=True, null=True, verbose_name='投稿日時[日本時間]（秒）'),
        ),
        migrations.AddField(
            model_name='movie',
            name='published_at_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='投稿日時[日本時間]（年）'),
        ),
    ]
