# Generated by Django 3.2.2 on 2021-08-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0012_company_other_option'),
        ('moviedatabase', '0031_auto_20210612_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['creator', 'name']},
        ),
        migrations.AddField(
            model_name='stationinmovie',
            name='line_name_customize',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='所属路線名カスタマイズ'),
        ),
        migrations.AddField(
            model_name='stationinmovie',
            name='line_service_on_other_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.lineservice', verbose_name='路線（その他の駅用）'),
        ),
    ]
