# Generated by Django 3.2.2 on 2021-08-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0032_auto_20210819_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='information_time_point',
            field=models.DateField(blank=True, null=True, verbose_name='情報の時点'),
        ),
    ]
