# Generated by Django 4.0.3 on 2022-08-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0033_part_information_time_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='parent',
            field=models.ManyToManyField(blank=True, to='moviedatabase.movie', verbose_name='親作品'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='related',
            field=models.ManyToManyField(blank=True, to='moviedatabase.movie', verbose_name='関連作品'),
        ),
        migrations.AlterField(
            model_name='part',
            name='information_time_point',
            field=models.DateField(blank=True, null=True, verbose_name='情報の日付'),
        ),
        migrations.AlterField(
            model_name='part',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='moviedatabase.movie', to_field='main_id', verbose_name='動画'),
        ),
    ]
