# Generated by Django 5.0.1 on 2024-01-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0034_alter_movie_parent_alter_movie_related_and_more'),
        ('songdata', '0009_alter_songnew_options_alter_artist_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='songnew',
            field=models.ManyToManyField(blank=True, related_name='movie', to='songdata.songnew', verbose_name='使用楽曲(楽曲全体)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part', to='moviedatabase.movie', to_field='main_id', verbose_name='動画'),
        ),
        migrations.AlterField(
            model_name='part',
            name='songnew',
            field=models.ManyToManyField(blank=True, related_name='part', to='songdata.songnew', verbose_name='使用楽曲(パート)'),
        ),
        migrations.AlterField(
            model_name='stationinmovie',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationinmovie', to='moviedatabase.part', verbose_name='動画パート'),
        ),
    ]
