# Generated by Django 3.2.2 on 2021-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210518_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit_all_channel',
            field=models.BooleanField(default=False),
        ),
    ]
