# Generated by Django 3.2.2 on 2021-05-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0019_updatehistory'),
        ('user', '0004_user_can_edit_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit_creator',
            field=models.ManyToManyField(blank=True, to='moviedatabase.YoutubeChannel', verbose_name='編集可能YouTubeチャンネル'),
        ),
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedatabase.creator', verbose_name='作者'),
        ),
    ]
