# Generated by Django 3.2.2 on 2021-05-19 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedatabase', '0021_updatehistory'),
        ('user', '0005_auto_20210519_1216'),
    ]

    operations = [
    ]
