# Generated by Django 3.0.2 on 2020-05-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelongsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='所属カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='事業者名')),
                ('short_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='略称1')),
                ('short_name_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='略称2')),
                ('name_kana', models.CharField(blank=True, max_length=200, null=True, verbose_name='事業者名読み')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='会社カラー')),
                ('sort_by_category', models.IntegerField(default=0, verbose_name='区分ごとの並び順')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='事業者区分')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='国名')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='路線名(鉄道要覧)')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='路線名')),
                ('name_sub', models.CharField(blank=True, max_length=200, null=True, verbose_name='路線区別名')),
                ('sort_by_company', models.IntegerField(default=0, verbose_name='事業者ごとの並び順')),
                ('is_freight', models.CharField(blank=True, max_length=200, null=True, verbose_name='貨物輸送')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.BelongsCategory', verbose_name='所属カテゴリー')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Company', verbose_name='事業者')),
            ],
        ),
        migrations.CreateModel(
            name='LineService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='路線名(運行系統名)')),
                ('name_sub', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='路線区別名')),
                ('head_company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='接頭会社名')),
                ('sort_by_company', models.IntegerField(default=0, verbose_name='事業者ごとの並び順')),
                ('is_formal', models.CharField(blank=True, max_length=200, null=True, verbose_name='正式区間')),
                ('is_service', models.CharField(blank=True, max_length=200, null=True, verbose_name='運行系統')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='路線カラー')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.BelongsCategory', verbose_name='所属カテゴリー')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Company', verbose_name='事業者')),
                ('line', models.ManyToManyField(blank=True, to='stationdata.Line', verbose_name='正式路線')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='都道府県名')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名')),
                ('name_kana', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名読み')),
                ('sort_by_line', models.IntegerField(blank=True, default=0, null=True, verbose_name='路線ごとの並び順')),
                ('open_ymd', models.DateField(blank=True, max_length=200, null=True, verbose_name='開業年月日')),
                ('close_ymd', models.DateField(blank=True, max_length=200, null=True, verbose_name='廃止年月日')),
                ('status', models.IntegerField(blank=True, choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], default=0, null=True, verbose_name='状態')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.ObjectCategory', verbose_name='名称カテゴリー')),
                ('group_station', models.ManyToManyField(blank=True, related_name='_station_group_station_+', to='stationdata.Station')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Line', verbose_name='路線')),
                ('pref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Prefecture', verbose_name='所在地')),
            ],
        ),
        migrations.CreateModel(
            name='StationServiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_history', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名(運行系統)')),
                ('numbering_head_history', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ナンバリング接頭辞')),
                ('numbering_symbol_history', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='路線記号')),
                ('numbering_middle_history', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ナンバリングハイフン')),
                ('numbering_number_history', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='駅番号')),
                ('sort_by_line_service_history', models.IntegerField(blank=True, default=0, null=True, verbose_name='路線(運行系統)ごとの並び順')),
                ('color_history', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='駅カラー')),
                ('changed_date', models.DateField(blank=True, max_length=200, null=True, verbose_name='変更年月日')),
                ('category_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.ObjectCategory', verbose_name='名称カテゴリー')),
                ('line_service_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.LineService', verbose_name='路線(運行系統)')),
                ('station_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Station', verbose_name='駅(正式)')),
            ],
        ),
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名(運行系統)')),
                ('numbering_head', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ナンバリング接頭辞')),
                ('numbering_symbol', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='路線記号')),
                ('numbering_middle', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ナンバリングハイフン')),
                ('numbering_number', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='駅番号')),
                ('sort_by_line_service', models.IntegerField(blank=True, default=0, null=True, verbose_name='路線(運行系統)ごとの並び順')),
                ('color', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='駅カラー')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.ObjectCategory', verbose_name='名称カテゴリー')),
                ('line_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.LineService', verbose_name='路線(運行系統)')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Station', verbose_name='駅(正式)')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='地方名')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Country', verbose_name='国')),
            ],
        ),
        migrations.AddField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Region', verbose_name='地方'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='prefs',
            field=models.ManyToManyField(blank=True, to='stationdata.Prefecture'),
        ),
        migrations.AddField(
            model_name='line',
            name='prefs',
            field=models.ManyToManyField(blank=True, to='stationdata.Prefecture'),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.CompanyCategory', verbose_name='事業者区分'),
        ),
    ]
