# Generated by Django 3.0.2 on 2020-05-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='種類')),
                ('text', models.TextField(max_length=500, verbose_name='内容')),
            ],
        ),
    ]
