# Generated by Django 3.0.2 on 2020-05-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0003_auto_20200530_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='group_station_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.Station', verbose_name='乗換駅(代表)'),
        ),
    ]
