# Generated by Django 3.0.2 on 2020-05-30 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0004_station_group_station_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationservice',
            name='group_station_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationdata.StationService', verbose_name='駅グループコード[運行系統]'),
        ),
    ]
