# Generated by Django 3.0.2 on 2020-06-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0005_stationservice_group_station_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationservice',
            name='is_representative',
            field=models.BooleanField(default=False, verbose_name='代表オブジェクト'),
        ),
    ]
