# Generated by Django 3.0.7 on 2020-06-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0009_auto_20200605_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], default=0, null=True, verbose_name='状態'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], default=0, null=True, verbose_name='状態'),
        ),
    ]
