# Generated by Django 3.2.2 on 2021-05-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0011_auto_20210510_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='other_option',
            field=models.BooleanField(default=False, verbose_name='その他の選択肢'),
        ),
    ]
