# Generated by Django 4.0.3 on 2022-08-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationdata', '0012_company_other_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['category', 'sort_by_category']},
        ),
        migrations.AlterModelOptions(
            name='companycategory',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='lineservice',
            options={'ordering': ['company', 'sort_by_company']},
        ),
        migrations.AlterModelOptions(
            name='stationservice',
            options={'ordering': ['line_service', 'sort_by_line_service']},
        ),
        migrations.AlterField(
            model_name='station',
            name='group_station',
            field=models.ManyToManyField(blank=True, to='stationdata.station'),
        ),
    ]
